- docker-compose.yml
Updated docker-compose.yml to pull containers from EdgeX Foundry Docker Hub account versus Dell Fuse account.
Signed-off-by: jim_white <james_white2@dell.com>
> Updated docker compose file to pull from EdgeX Foundry Docker Hub

- docker-compose.yml
Commented sample entries for new device services
Signed-off-by: Tyler Cox <tyler_cox@dell.com>
> Adds entries for new device services

- README.md
- linux_setup.sh
Signed-off-by: chadyoungdell.com <chad.young@dell.com>
> adding a linux setup shell script and modified README

- docker-compose.yml
> Adding back config-seed to docker-compose

- MODULES
- README.md
- prepare-environment.sh
- update-packages.sh
`prepare-environment.sh`
If you launch the script without parameters, it downloads the modules you need to work with edgex.
Also accepts a list of modules as parameters to prepare the development environment. Valid modules are in MODULES file. Useful to automate tasks.
`update-packages.sh `
Updates the packages you have installed.
`MODULES`
List of available modules to be installed.
> Added two scripts to prepare the environment automatically:

- docker-compose.yml
Closes #12
Signed-off-by: Tyler_Cox <Tyler_Cox@dell.com>
> Fixes device service name

- README.md
- create-containers.sh
- prepare-environment.sh
- reset-dockers.sh
reset-dockers.sh - This script removes all containers and images from your environment. Very useful for development
create-containers.sh - This script creates containers and images defined in internal variable `DOCKER`
> Added two new useful scripts

- docker-compose-dev.yml
- docker-compose.yml
- run-it.sh
Adds developer compose file targeting nightly builds.
Updates run-it.sh to allow for targeting different compose files with first argument.
> Developer compose

- docker-compose-dev.yml
- docker-compose.yml
Usefull when developing a microservice listening to data zeromq .
> Expose zeromq port also to host

- mongoAdminOperStateUpdate.js
Use for migrating from deprecated enums in existing Mongo records
Signed-off-by: Tyler_Cox <tyler_cox@dell.com>
> Adds Admin and Operating State Migration Script

- run-it.sh
Added a missing -f $COMPOSE_FILE when executing docker-compose.
> Fix run-it.sh

- compose-files/docker-compose-preview-california-0.5.0.yml
> added env to allow Go Lang export services to work properly

- clean_shell.bat
- init_shell.bat
Last version of mongodb is 3.6, so i changed the default version of it.
Moreover, I add the comments to advert to change the location or version as user want.
+ Signed off added. Sorry for the confusion.
Signed-off-by: YANG YOU SUNG - DevFallingstar <stardung86@gmail.com>
> Modify clean_sheel.bat and init_shell.bat (Signed off)

- compose-files/docker-compose-california-0.5.2.yml
Add new docker-compose file for california preview release 0.5.2.  This includes new Docker Hub images for all Go services.
> Add docker-compose file for preview 0.5.2

- compose-files/README.md
- compose-files/docker-compose-california-0.6.0.yml
- compose-files/docker-compose.yml
docker compose files for California release.  Updated README and updates "latest" compose files too.
> new compose file for California

- compose-files/README.md
> update README to indicate lastest update date

- linux_setup.sh
> Fixes #56 and Fixes #55 - typos in comments of the shell script

- clean_mongo.js
#66 
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Include clearing of logging database

- compose-files/docker-compose-california0.6.1.yml
> docker compose file for California 0.6.1 images - using Nexus

- compose-files/docker-compose-delhi-0.7.0.yml
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
> initial Delhi compose file

- compose-files/security/docker-compose-delhi-0.7.0.yml
Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>
> Add docker compose file that enables security service for delhi.

- compose-files/docker-compose-delhi-0.7.0.yml
- compose-files/docker-compose.yml
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
> Delhi Release Compose files added

- compose-files/security/docker-compose-delhi-0.7.0.yml
Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>
> Change docker images to delhi version

- compose-files/docker-compose-delhi-0.7.1.yml
- compose-files/docker-compose-nexus.yml
- compose-files/docker-compose.yml
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
> docker compose files for delhi dot 0.7.1

- compose-files/README.md
- compose-files/docker-compose-redis-delhi-0.7.1.yml
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
> addition of the redis compose file and updated the compose file readme

- clean_mongo.js
- init_mongo.js
Changes to the init_mongo.js and the clean_mongo.js in preparation for the new scheduler db.
Adding collection indexes
Adding cleanup script to remove entries from the interval and intervalAction collections.
Signed-off-by: xmlviking <ecotter@gmail.com>
> adding script changes for the scheduler database

- compose-files/docker-compose-edinburgh-1.0.0.yml
- compose-files/docker-compose-redis-edinburgh-1.0.0.yml
See #111 and [edgex-go/pull/1348](https://github.com/edgexfoundry/edgex-go/pull/1348)
Tested in my sandbox. Dependent on [edgex-go/pull/1376](https://github.com/edgexfoundry/edgex-go/pull/1376).
> PR for #111: Create Edinburgh Docker Compose files

- compose-files/docker-compose-edinburgh-1.0.0.yml
- compose-files/docker-compose-nexus.yml
- compose-files/docker-compose-redis-edinburgh-1.0.0.yml
- compose-files/docker-compose.yml
Fix #85
For the Edinburgh release, upgrade Consul in docker-files to use v1.3.1
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Update Consul 1.3.1 in docker-compose files

- compose-files/docker-compose-edinburgh-1.0.0.yml
- compose-files/docker-compose-nexus.yml
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
> Fixes #122, addition of proper security services for Edinburgh

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Update nightly build to version 1.1.0 (Fuji)

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This PR is to fix the issue #141 
> Fix issue #141: use the latest docker image names

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Fixes: https://github.com/edgexfoundry/developer-scripts/issues/160
> Rules Engine Image Name is Incorrect

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Fixes: https://github.com/edgexfoundry/developer-scripts/issues/173
> Update support-rulesengine to newest version

- releases/nightly-build/compose-files/docker-compose-nexus.yml
See comments from PR #178 to remove the commented vault-config volume from the compose file
> Follow-up PR for PR #177 comments: removing commented vault-config from exportdistro

- releases/README.md
- releases/fuji/compose-files/docker-compose-fuji-no-secty.yml
- releases/fuji/compose-files/docker-compose-fuji.yml
- releases/fuji/compose-files/docker-compose-nexus-fuji-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
> Create Fuji release docker-compose directory/files

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
Fix #154:https://github.com/edgexfoundry/developer-scripts/issues/154
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
> Add ARM64 versions of docker-compose files for nexus release

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
> Version bump of Vault container (to 1.3.1)

- releases/fuji/compose-files/docker-compose-fuji-no-secty.yml
- releases/fuji/compose-files/docker-compose-fuji.yml
- releases/fuji/compose-files/docker-compose-redis-fuji-no-secty.yml
Fix #199 once 1.1.1 images are built.
> Update device services' image version number

- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
Fix https://github.com/edgexfoundry/developer-scripts/issues/207
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
> Add ARM64 redis compose file for nexus release

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
> Bump version of postgres container (to 12.1-apline)

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
> (feat)[security-services] Update Kong version to 2.0.1

- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Fix #224
add "-cp" to config-seed command option
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
> Update config-seed command in nightly compose file

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Addresses #189
This `draft` PR is dependent on https://github.com/edgexfoundry/edgex-go/pull/2445 being merged first and all the docker images created in Nexus.
> feat: Remove config-seed and add environment overrides

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Removed the global override that enabled remote logging
Remove proxy setup's logging overrides that are no longer needed.
close #245
> feat(logging): Remove remote logging overrides

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Replace rulesengine with kuiper in the compose-file
> Replace rulesengine with kuiper in the compose-file

- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Fixes #225 
This compose file is tightly coupled to the related PRs on edgex-go and go-mod-boostrap.
Please see
[go-mod-bootstrap PR#68](https://github.com/edgexfoundry/go-mod-bootstrap/pull/68)
[edgex-go PR#2497](https://github.com/edgexfoundry/edgex-go/pull/2497)
Signed-off-by: Andre Srinivasan andre@redislabs.com
> Compose file changes for secure Redis

- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Fixes #255.
This is tightly coupled to changes in [edgex-go PR#2497](https://github.com/edgexfoundry/edgex-go/pull/2497).
> Cleanup Redis5 password handoff

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
> Use file/stdout for logger

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
> fix: Properly set the port override for App Service Configurable

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
> Remove extraneous Logging_File env var in logging section of Compose files

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
Removed the following overrides where they occurred.
- Databases_Primary_Password
- Databases_Primary_Username
> refact: Remove unneeded overrides for DB username & password

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
- releases/nightly-build/compose-files/docker-compose-portainer.yml
with the exception of the Kong proxy ports bind all services to 127
I believe this would close #190
> bind to 127 with the exception of Kong proxy ports

- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Fixes #273 and [edgex-go #2542](https://github.com/edgexfoundry/edgex-go/issues/2542)
> Wait for content in password file

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Added REST device service to be running by default
closes #277
> feat: Enable REST Device service as one of the default services running.

- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
Fixes #284 
Wrong docker image referenced.
> bug: Correct docker image

- releases/geneva/docker-compose-geneva-mongo-arm64.yml
- releases/geneva/docker-compose-geneva-mongo-no-secty-arm64.yml
- releases/geneva/docker-compose-geneva-mongo-no-secty.yml
- releases/geneva/docker-compose-geneva-mongo.yml
- releases/geneva/docker-compose-geneva-redis-arm64.yml
- releases/geneva/docker-compose-geneva-redis-no-secty-arm64.yml
- releases/geneva/docker-compose-geneva-redis-no-secty.yml
- releases/geneva/docker-compose-geneva-redis.yml
- releases/geneva/docker-compose-portainer.yml
Created Geneva docker compose files
Add comments for deprecating Support Rules Engine and Mongo
closes #282 & #272
> feat: Create Geneva docker compose files

- releases/README.md
- releases/geneva/compose-files/docker-compose-geneva-mongo-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-redis.yml
- releases/geneva/compose-files/docker-compose-geneva-ui-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-ui.yml
Also switched UI to use `network-mode: host` 
closes #289
> refactor: Move UI out of composes files into its own optional compose file

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-base.yml
feat: Add read-only flag to consul
close #299
https://github.com/edgexfoundry/developer-scripts/issues/299
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
What kind of change does this PR introduce?
consul docker container has read and write permissions
https://github.com/edgexfoundry/developer-scripts/issues/299
Issue Number: 299
consul will have read only permission
no
no
> feat: Add read-only flag to consul

- releases/nightly-build/compose-files/Makefile
make get-token fails
make get-token works
To test this PR.
1. run `make run`
2. run `make get-token`
> fix: Fix get-token make command to work properly

- Jenkinsfile
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
Enables recheck from comments
> ci: add recheck trigger

- compose-builder/docker-compose-base.yml
version check is failing
Disabled version check
Temporary fix until SDK can be bumped to 2.0.0
> fix: Disable App Service Config's version check

- compose-builder/docker-compose-base.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Old unused `logging-data` volume still exists in compose files.
Old unused `logging-data` volume no longer still exists in compose files.
> refactor: Remove old volume for logging data

- compose-builder/add-device-camera.yml
service name and port for device camera incorrect
service name and port for device camera now correct
> fix: Correct service name and port for device camera

- compose-builder/.env
- compose-builder/add-security.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus.yml
currently, kong is on 2.0.x version and arm64 is ubuntu-based version
both versions of amd64 and arm64 of kong's docker images are on 2.3-alpine versions
- [x ] No
> build(kong): upgrade kong's image to 2.3-alpine

- compose-builder/add-device-grove.yml
device-grove compose file missing devices section
device-grove compose file now has devices section
- [x ] No
no
> fix: Add devices section in device-grove compose file
