edgexfoundry/developer-scripts

- README.md
- run-it.sh
Based on
https://wiki.edgexfoundry.org/display/FA/Get+EdgeX+Foundry+-+Users
script makes sure services are started in the right order and with
enough waiting time for the dependencies to become live.
> Add script to run services in the correct order

- docker-compose.yml
Every time a docker is started it is also starting config-seed and mongo-seed. As those dockers are also started from runit.sh in the correct order there is no need to waste resources when starting all the services.
> Do not launch config-seed and mongo-seed each time a docker is started

- docker-compose.yml
It is no longer needed after docker-edgex-mongo is executing the init_mongo.js every time it starts.
This change should not be merged until the updated docker-edgex-mongo is pushed to the docker hub.
> Remove mongo-seed docker

- docker-compose.yml
- run-it.sh
To avoid high memory peaks during docker deployment, we have merged consul configuration and config-seed.
Modified docker-compose and run-it removing all consul references since now it is launched from config-seed
This PR requires the PR in core-config-seed
> Merged consul and config-seed into one docker

- init_mongo.js
> removed device manager from the init script

- run-it.sh
*the original script uses the sleep mode to interval the starting order.
*The interval time is not accurate, for example, my machine performance is small, 
the start interval will need longer.
*There is a dependency between front and back micro services,
If the interval between the startup services is not well controlled, the latter service starts to fail.
*The new script has been tested many times, and it can be accurately controlled before and after.
It has been maximized to reduce the dependency of third party shell command, 
but for config-seed services, the command curl is necessary.
Signed-off-by: Huaqiao Zhang <huaqiaoz@vmware.com>
> more precise control of the start order 

- startdb-no-auth.bat
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
MongoDB won't start if the specified directory doesn't exist, so I had to manually create it. I thought it would be helpful to have the script do a check and then create the directory for me.
> Create C:\Users\Public\mongodb\db directory if it doesn't exist.

- clean_mongo.js
- init_mongo.js
#99 
Remove export client entries in clean_mongo.sh . Also remove serviceMapping entries so the `init_mongo.sh`/`clean_mongo.sh` loop is clean.
> clean_mongo.sh should remove export client entries

- compose-files/security/docker-compose-delhi-0.7.0.yml
* Fix incorrect indentation on start of vault service definition
* Set vault image to use the 0.2.0 tag
* Fix vault-worker image name to use the -go suffix
* Set vault-worker image to use the 0.2.0 tag
* Set edgex-proxy image to use the 0.2.0 tag
* Add portainer_data to list of volumes for the portainer service
> Fix broken docker-compose for security services. Fixes #102

- compose-files/docker-compose-delhi-0.7.1-arm64.yml
This compose-file was built to be used on Raspberry-pi 3 with BalenaOS (64bit BETA version). It can be used on any device with the same architecture and a linux based OS. It has a balance between functionality and RAM/CPU load. Random-Int device service is loaded by default for testing purposes. Not stable enough for production env (due to mongo-DB excess RAM usage).
Signed-off-by: Odysseas Lamtzidis <odyslam@gmail.com>
> Docker-Compose for Raspberry Pi-3 (arm64)

- compose-files/docker-compose-edinburgh-1.0.0.yml
Fix #115 
Updating the docker-compose configuration entries for the new device-snmp-go.
Including the image name as it will be named for the edinburgh release.
Signed-off-by: xmlviking <ecotter@gmail.com>
> Updating docker-compose for edinburgh with device-snmp-go

- init_mongo.js
Fix #116
Related to: EdgeX-GO #1286
Add an index to the reading collection for the device field which will
allow for more effective deletions when deleting all readings associated
with a specific device. This will prevent the database manager from
performing a full scan.
Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>
> Add index to Mongo for Reading's device field

- releases/nightly-build/compose-files/docker-compose-nexus.yml
Because Vault is going to be integrated in 'docker-edgex-mongo', 
now mongo containers should depends on both:
- vault-worker (unseal vault) and
- vault-config volume (contains vault root-token)
- change the mongo image version
Signed-off-by: difince <dianaa@vmware.com>
> Mongo start depending on vault-worker and vault-config volume

- project-metrics/README.md
- releases/README.md
- releases/edinburgh/compose-files/README.md
Updates referenced Edinburgh file names in README.md.
Corrects misspelling.
Fixes: https://github.com/edgexfoundry/developer-scripts/issues/134
> Outdated docker-compose (Edinburgh) links in README markdown

- README.md
The link is currently pointing to:
https://wiki.edgexfoundry.org/display/FA/Get+EdgeX+Foundry+-+Users
Which has been replaced by:
https://docs.edgexfoundry.org/Ch-GettingStartedUsers.html
This PR updates the link
> Fix link to Getting Started Guide

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
This PR fix the issue #144 
Both non-security docker-compose files has the environment variable `EDGEX_SECURITY_SECRET_STORE` added into common shared section and the value set to `false`.
```sh
docker-compose -f docker-compose-nexus-no-secty.yml up -d
```
Wait until all services up.  After that to test and see if number of services up-running is correct, use:
```sh
docker ps | grep -E "edgex-+" | test $(wc -l) -eq 15 && echo "Pass" || echo "Failed"
```
One should expect to see "Pass".
```sh
docker-compose -f docker-compose-nexus-no-secty.yml down
```
> Fix issue 144: add edgex-security-disable env variable into docker-compose files

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This PR attempt to fix issue #150 
Remove bind mount on the host system as it causes the problem of white-list mount of MacOs
Change the tmpfs inside the docker container so that by default deploy directory exists
```sh
docker-compose -f docker-compose-nexus.yml up -d
```
```sh
docker-compose -f docker-compose-nexus.yml down
```
> Fix issue #150: MacOS compatibility issue of /run

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This PR attempts to fix issue #152 
- Fix the flag name in edgex-vault-worker (insecureSkipVerify)
- Add the missing vault-config volume from vault itself
- Add the missing flags in edgex-proxy
```sh
docker-compose -f docker-compose-nexus.yml up -d
```
After docker-compose up, run this:
```sh
sleep 15; docker ps -a | grep vault-worker | grep "Exited (0)" && echo "Pass" || echo "Failed"
```
One should expect to see `Pass` as `vault-worker` is one-time shot docker micro-service.
> Fix issue #152: vault-worker micro service fails to start in nightly secure docker-compose

- LICENSE
While the LICENSE file was first committed by myself (see #105), the project's origin was from Dell in 2017 as per git history.
CC @jpwhitemn
> LICENSE: retroactively add proper Copyright to license

- releases/nightly-build/compose-files/docker-compose-nexus.yml
Fixes #165 
Reverted changes to docker-compose to enable generate mode of operation.
Due to code freeze, could not implement additional changes to fully transition.
Implementation of PKI uses legacy functionality present in security-secrets-setup
Need to remove VAULT_LOCAL_CONFIG because it duplicated the local.hcl file that was injected at container build time.
The result was Vault creating duplicate listeners and failing
because the cluster_address was attempted to be bound twice.
> Fix issue #165: Edgex-vault failing to start listener with bind address already in use

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This option defaults to false and so we shouldn't specify it at all for either of these containers.
See https://github.com/edgexfoundry/edgex-go/pull/1985#issuecomment-546073590
CC @jim-wang-intel @bnevis-i @tingyuz
> nightly-build/docker-compose-nexus.yml: remove insecureSkipVerify arg

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This PR implements dependency ordering for the Kong services. It is dependent on the new updates to the docker containers implemented in:
These have been merged, so this should run without modification to this PR and you can use the containers from nexus.
After this, you can see that kong-db, kong-migrations, and then finally kong all become active in the consul services page.
Also check that kong-migrations performs the check on kong-db before actually running the migraiton:
```
$ docker logs kong-migration
+ cd /consul/scripts
+ LD_LIBRARY_PATH=.
+ export LD_LIBRARY_PATH
+ curl -s -G edgex-core-consul:8500/v1/agent/checks
+ /consul/scripts/jq -r '.[] | select(.ServiceName == "kong-db") | .Status == "passing"'
+ '[' true '=' true ]
bootstrapping database...
migrating core on database …
```
> nightly-build/docker-compose-nexus.yml: implement dependency ordering for Kong

- releases/nightly-build/compose-files/docker-compose-nexus.yml
The consul svc status script from docker-edgex-consul can now be used to wait for services to be ready as defined by Consul before running their full command. 
Note we use `entrypoint` to override a hard-coded ENTRYPOINT in the image, we can't use command like we do for the other containers (i.e. kong and vault and postgres, etc.)
Also add the vault-config volume to consul so that consul can check for the existence of the TLS files.
This PR depends on a PR in edgex-go which will enable running these entrypoint overrides in the security-secretstore-setup and security-proxy-setup images, because the current is missing curl and the latter is based on scratch and thus has no `/bin/sh` or curl. That edgex-go PR is here: https://github.com/edgexfoundry/edgex-go/pull/2075. 
This PR also depends …
> nightly-build/docker-compose-nexus.yml: use consul script for sec svcs

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
New default is for app-service-configurable running rules-engine profile to provide the event message to the rules engine.
closes #168
> feat(app-service-configurable-rules): Replace Export services with app-service-configurable

- releases/nightly-build/compose-files/docker-compose-nexus.yml
Upgrade Kong docker image to version 1.3.0
> Upgrade Kong to 1.3.0 for x86

- releases/nightly-build/compose-files/docker-compose-nexus.yml
Fixes #177 
For core services, vault-config volumes are missing.  Add vault-config volume mapping into core-services.
> Fixes the issue #177: add missing vault-config volume for core services in security nightly compose

- releases/nightly-build/compose-files/docker-compose-nexus.yml
edgex-mongo needs security-secretstore-setup to have run before it can use the root token to access Vault and configure the database passwords stored in Vault to be usable with MongoDB.
Note that because the edgex-mongo image is Ubuntu based, this requires a corresponding change to the consul-svc-healthy.sh script to work since that script currently is hard-coded to assume the base image is Alpine/musl based. That PR is open here: https://github.com/edgexfoundry/docker-edgex-consul/pull/7
To test this, you will still need to build the following docker images locally:
- docker-edgex-security-secretstore-go
- docker-edgex-security-proxy-go
- docker-edgex-volume
- docker-edgex-consul
- docker-edgex-mongo
Then after building those locally, all from the fuji branch (or in the case of …
> releases/nightly-build/docker-compose-nexus.yml: make mongo wait for sec svcs

- releases/nightly-build/compose-files/docker-compose-nexus.yml
This PR is to match the latest states from codes changes built from the master.
This updates of compose is to make the compose file uses the latest docker images built from master and specifically, the changes of customized edgex-vault into two.  
This one also depends on the merging master of this PR https://github.com/edgexfoundry/edgex-go/pull/2214 before the vault-worker can be up and running.
Also reference to issue #1716
Once this one is stabilized, then will make a synced changes on the compose of black-box testing repo, too.
> Update the nightly docker-compose file

- releases/nightly-build/compose-files/docker-compose-nexus.yml
CA certificate was mounted as `ca/pem` instead of `ca.pem`
> fixup! Update the docker-compose file to match the latest states from codes on the master (#184)

- .gitignore
- MODULES
- README.md
- clean_mongo.js
- create-containers.sh
- init_mongo.js
- project-metrics/fetch_repos.sh
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- run-it.sh
Related to: https://github.com/edgexfoundry/edgex-go/issues/2218
> Remove Export Services for Geneva Release

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Blackbox testing scripts will shortly in the future use developer-scripts
to start the container environment needed for blackbox tests.
This script back-ports the selinux volume flags that are needed
for the docker-compose to run successfully in the blackbox testing
environment.
Fixes #196 
> Backport of SElinux-compatible volume flags from blackbox-testing

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Fixes https://github.com/edgexfoundry/blackbox-testing/issues/368
This (should) prevent the following error in blackbox testing:
chmod: changing permissions of '/proc/self/fd/1': Permission denied
chmod: changing permissions of '/proc/self/fd/2': Permission denied
nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)
> Allocate a tty to kong

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
Fixes https://github.com/edgexfoundry/blackbox-testing/issues/369
Addresses https://github.com/edgexfoundry/edgex-go/issues/2171
> Use security version of docker-edgex-consul for arm64.

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Modifies the secrets volume of edgex-proxy so that it has access
to its per-service token.  Remove the volume mount to the actual
TLS certificate since edgex-proxy gets the TLS cert from the
secret store.  Fix dependency on edgex-proxy (actually depends
on vault-worker to upload the TLS cert, not vault) and
remove kong-db (kong already depends on kong-db).
Address https://github.com/edgexfoundry/edgex-go/issues/1930
> Enable edgex-proxy to use per-service token instead of root token.

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
vault-worker needs to be able to write secrets tokens for
all microservices.
Fixes https://github.com/edgexfoundry/blackbox-testing/issues/381
> Fix vault-worker on arm64 security build so that it mounts all secrets volumes

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Partially-fixes https://github.com/edgexfoundry/edgex-go/issues/2318  (this PR needs to go first)
Testing instructions forthcoming (need to touch several repos)
> Expose non-root Vault tokens to services currently needing root token.

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Reduce the exposure of security-sensitive assets (i.e.
Vault root token) by unmapping it from the service containers;
these containers already have per-service tokens mapped
to them.  Also add a tmpfs /run to vault-worker to prevent
the token private passed between security-secretstore-setup
and security-file-token-provider from being stored on
persistent media on the host.
Fixes #2318
> feat[security-services]: Reduce exposure of sensitive assets

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Fixes #215 
Tested via blackbox tests. See also [blackbox-testing PR #385](https://github.com/edgexfoundry/blackbox-testing/pull/385)
Signed-off-by: Andre Srinivasan <andre@redislabs.com>
> Initial Docker Compose files with for Redis default

- releases/fuji/compose-files/docker-compose-fuji.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
https://github.com/docker-library/postgres/pull/658
Before
```
docker-compose -f docker-compose-nexus.yml ps
Name                     Command               State                                                           Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
edgex-core-consul   docker-entrypoint.sh agent ...   Up       8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8400->8400/tcp, 0.0.0.0:8500->8500/tcp, 8600/tcp, 8600/udp
edgex-files         /bin/sh -c /usr/bin/tail - ...   Up
kong                /docker-entrypoint.sh /bin ...   Up       0.0.0.0:8000->8000/tcp, 0.0.0.0:8001->8001/tcp, 0.0.0.0:8443->8443/tcp, 0.0.0.0:8444->8444/tcp …
```
> Fix postgres-db initialization requires a password to start now

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
Fixes https://github.com/edgexfoundry/edgex-go/issues/2383
Fixes https://github.com/edgexfoundry/docker-edgex-consul/issues/21
This fix addresses a race condition for mongodb initialization
wherein the secret store is set up, but has not generated
per-sevice Vault tokens, nor committed mongodb passwords to
the secret store.  This fix introduces a sentinel file that
is used to indicate secretstore-setup completion without
giving access to the secretstore to an untrusted component (consul).
> fix[security-services]: Address race condition for mongodb initialization

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
edgex-go use the RedisDB as default DB, so docker-compose needs to override the database config to enable the MongoDB
https://github.com/edgexfoundry/edgex-go/blob/master/cmd/support-scheduler/res/docker/configuration.toml#L31
Fix #228
> Provide the MongoDB config via env variable

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
App Services Configurable Rules Engine service doesn't need secrets so as a temporary fix
turn off secerity just on this service so the un-configured Secret Client isn't
created causing service to fail. This is a temporary fix waiting on
https://github.com/edgexfoundry/app-functions-sdk-go/issues/315 to be addressed.
closes https://github.com/edgexfoundry/blackbox-testing/issues/425
> fix: Disable security for App Services Configurable Rules Engine service

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Fixes https://github.com/edgexfoundry/developer-scripts/issues/242
Fixes https://github.com/edgexfoundry/developer-scripts/issues/220
Fixes https://github.com/edgexfoundry/developer-scripts/issues/213
Added the new environment variables to the consul services in each of
the compose files. The vars, EDGEX_DB and EDGEX_SECURE are utilized in
an entrypoint script in the docker-edgex-consul image that initializes
default config and script files based on these environment variables.
These variables are NOT required (as they have defaults if the system
can't find them), however, it is encouraged to use them so that
configuration is explicitly set, and the developers happen to know what
might be going on in the event of a misconfigured consul service.
Signed-off-by: Beau Frusetta …
> fix: Consul health check runtime config

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
Fixes miss for Clients.VirtualDevice in https://github.com/edgexfoundry/edgex-go/blob/master/cmd/security-proxy-setup/res/configuration.toml
> fix[blackbox]: Override docker host name for edgex-device-virtual

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-portainer.yml
Portianer now can be started and stopped separately from all the other services. It will no longer be stopped when the other services are brought down.
> refact(portainer): refactor compose files to move Portainer to its own file.

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
The purpose of this PR is to remove the ~100MB dependency of edgex-volume from the docker-compose files, and make modifications to the service dependencies to reflect the [service dependency graph](https://slack-files.com/TE66WRR3Q-F01148L6M7U-9a41e95836).  Several changes have been made to minimize spurious differences across mongo/redis, no-security/security, and amd64/arm64 versions of the compose files.  It is expected that these changes will also make it easier to remove the logging service in a future PR.
cc: @lenny-intel, @tingyuz, @andresrinivasan, @cloudxxx8 
Please ensure that you have the latest versions of all containers (`docker-compose -f whatever.yml pull`) and state (`docker volume prune`, `rm -fr /tmp/edgex/secrets`) before bringing up the stack.
Signed-off-by: Bryon …
> cleanup: Remove edgex-volume and correct service dependencies

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
No longer need to skip version check. It handles master as the version from Core Data
No longer need to override edgex_registry. This is default in command line for Config Provider
closes #267
> refactor: Remove settings no longer needed on app-service-rules

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Support logging has been deprecated via commenting out appropriate sections in the compose files.
closes #270
> refactor: Deprecated the Support Logging service

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
closes #275
If existing Fuji deployment is upgraded to Geneva, remote logging will be enabled in the configuration stored in Consul. 
This PR explicitly disables remote logging with environment override for this scenario
> fix: Explicity disable remote logging to override any old configuration used

- releases/nightly-build/compose-files/docker-compose-nexus-mongo-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-mongo.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-redis.yml
Also, fixed comment for Logging Host in all compose files
closes #279
closes https://github.com/edgexfoundry/edgex-go/issues/2543
> fix: Restore override for Notifications Host in Mongo compose file

- releases/geneva/compose-files/docker-compose-geneva-mongo-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-redis.yml
- releases/geneva/compose-files/docker-compose-geneva-ui-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-ui.yml
- Updated the versions of the services impacted by this dot release
- Cleaned up the `network` section so it is consistent across all the services
- Added missing override `Clients_Data_Host` for device services that have the Core Data client specified differently.
- Added UI back to the edgex network
> fix: Geneva 1.2.1 dot release updates

- releases/geneva/compose-files/docker-compose-geneva-mongo-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-mongo.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty-arm64.yml
- releases/geneva/compose-files/docker-compose-geneva-redis-no-secty.yml
- releases/geneva/compose-files/docker-compose-geneva-redis.yml
Updated docker-compose files of Geneva to use v1.2.2 virtual device service
Signed-off-by: Felix Ting <felix@iotechsys.com>
> fix: Geneva device-virtual-go v1.2.2 release updates

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-base.yml
Port 8400 isn't used by Consul and causing issue when deployed with load balancer which tries to ping the port for a health check.
Close #296
> fix(consul): Removed exposing of port 8400

- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-add-device-services.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-add-mqtt.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-add-security.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-base.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-ui.yml
feat: Add read-only flag to all services
close #1921
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
The following containers require read/write permission to modify files within the container and do not support the read_only flag:
- device-virtual
- vault
- consul
- rulesengine
What kind of change does this PR introduce?
docker containers have read and write permissions
https://github.com/edgexfoundry/edgex-go/issues/1921
Issue Number: 1921
docker containers will be read only unless required to write.
no
no
> feat: Add read-only flag to all services

- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-add-security.yml
- releases/nightly-build/compose-files/source/docker-compose-nexus-base.yml
Consul health check scripts are copied into /consul/scripts directory
even if related health-checks needed for security are not enabled.
Make the consul-scripts volume available in all configurations,
to avoid failure of the entrypoint script.
Fixes #301
> fix: Make /consul/scripts directory writable even in non-secure consul.

- releases/nightly-build/compose-files/source/Makefile
- releases/nightly-build/compose-files/source/README.md
Fix the issue of mismatch docker image versioning on `"make gen dev "` in generated docker-compose.yml with the ones from
running `"make docker"` out of `"edgex-go"` repo.
eg.: changes from "master-dev" to "0.0.0-dev"
Closes: #321 
> fix(makefile): make gen dev to generate the matched docker core service images versioning

- Jenkinsfile
Initialize pipeline to run edgex-taf smoke tests.
**Note:** Smoke tests take about 30-35 minutes to run.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.
N/A
> ci: init Jenkins smoke test pipeline

- .gitignore
- compose-builder/README.md
- compose-builder/add-security.yml
- compose-builder/database-security.env
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Resolves #332 
Add new security-bootstrap-redis service
This PR is dependent on actually adding the service to edgex-go. See [edgex-go issue #2503](https://github.com/edgexfoundry/edgex-go/issues/2503)
I'm creating this PR for the purposes of review. Please do not merge yet.
> feat: Add security-bootstrap-redis service

- compose-builder/docker-compose-base.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Data does not persist and container was not read-only
#320 
Added the ability to persist streams/rules data when the kuiper container is
recreated. Also made the container read-only.
> feat: Persistent Streams & Rules with RO Container

- compose-builder/Makefile
- compose-builder/get-api-gateway-token.sh
Get token uses deprecated proxy-setup addUser command to generate API Gateway token
Get token now uses new secrets-config proxy addUser & jwt commands to generate API Gateway token.
> feat: Use secrets-config to generate API Gateway token

- compose-builder/Makefile
- compose-builder/README.md
- compose-builder/get-api-gateway-token.sh
- compose-builder/upload-api-gateway-cert.sh
Add a new makefile target for compose-builder: upload-tls-cert
This can be used to setup a bring-your-own (BYO) TLS certificate for Kong proxy server in an Edgex docker-compose stack
Closes: edgexfoundry/edgex-go#1926, edgexfoundry/edgex-go#1922
- [X ] Docs have been added / updated (for bug fixes / features)
Currently, there is no make target to upload Kong's TLS certificate.
New make file target `upload-tls-cert` is added.
- [X ] No
Are there any specific instructions or …
> feat(security): Add upload-tls-cert makefile target

- compose-builder/add-security.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
With the Vault's backend storage been changed to filesystem instead of Consul,  will no longer depend on  in the compose file.
This together with edgex-go's change and edgex-consul's vault healthy check removal shall close the issue edgexfoundry/edgex-go#2882 .
Vault depends on Consul
Fixes edgexfoundry/edgex-go#2882
Vault will not depend on Consul directly
**Note:  For this compose up …
> feat(security): Remove Vault dependency on Consul

- compose-builder/add-security.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
Kong service definition splits migrations and persistent service into 2 separate services, leaving migrations a dead container after it completes execution.
#365 
Modified the main kong container to run the command issued from the kong migration container. Both containers derive from the same base and their service definitions are identical. Net result - 1 less container.
n/a
> feat: Combine Kong Service Containers

- compose-builder/add-device-bacnet.yml
- compose-builder/add-device-camera.yml
- compose-builder/add-device-grove.yml
- compose-builder/add-device-modbus.yml
- compose-builder/add-device-mqtt.yml
- compose-builder/add-device-random.yml
- compose-builder/add-device-rest.yml
- compose-builder/add-device-snmp.yml
- compose-builder/add-device-virtual.yml
- compose-builder/add-mqtt-messagebus.yml
- compose-builder/add-security.yml
- compose-builder/docker-compose-base.yml
- compose-builder/docker-compose-ui.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
UIDs within containers running in EdgeX can request and gain elevated privilege which creates a security risk to the processes running within the containers.
#143 
All services, under the orchestration of docker-compose, are now prohibited from gaining elevated privilege through the Docker security option "no-new-privileges" set in the compose service defintions.
N/A
> feat(security): Set "no-new-privileges" on Svcs

- compose-builder/add-security.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
The security-secrets-setup docker image will be removed once the related PRs removing the secrets-setup component from `edgex-go` and `edgex-core-consul` checkers are merged.
- [x ] Tests for the changes have been added (for bug fixes / features)
Current `secrets-setup` is still on docker-compose file.
No docker `security-secrets-setup` service in the compose files any more
- [X ] No
Need …
> feat(security): Remove secrets-setup service from compose

- compose-builder/add-security.yml
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
A mock security-bootstrapper added and do nothing for now.
Dependencies on security-bootstrapper for other containers are added in based on the [ADR security bootstrapping](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/security/0009-Secure-Bootstrapping.md#to-be-startup-flow)  "TO-BE" diagram.
Shared volume `edgex-init` is newly added for preps of future entrypoint script injection from security-bootstrapper.
Closes: #348 
A new mock container for …
> feat(security): add mock security-bootstrapper

- compose-builder/Makefile
- compose-builder/add-asc-http-export-secure.yml
- compose-builder/add-asc-mqtt-export-secure.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus.yml
Makefile with make gen dev asc-http-s asc-mqtt-s now generates the correct ADD_SECRETSTORE_TOKENS value in secure mode.
Fixes: #376
ADD_SECRETSTORE_TOKENS not generated correctly when both asc-http-s and asc-mqtt-s were specified.
ADD_SECRETSTORE_TOKENS now is generated correctly when both asc-http-s and asc-mqtt-s are specified.
- [x ] No
> feat(build): fix bug of generating incorrect ADD_SECRETSTORE_TOKENS value

- compose-builder/.env
- compose-builder/Makefile
- compose-builder/README.md
- compose-builder/add-asc-http-export-secure.yml
- compose-builder/add-asc-http-export.yml
- compose-builder/add-asc-mqtt-export-secure.yml
- compose-builder/add-asc-mqtt-export.yml
- compose-builder/add-taf-app-services.yml
- compose-builder/docker-compose-base.yml
- compose-builder/gen-header
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-no-secty.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus-ui.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-no-secty.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus-no-secty.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus.yml
Enhance the capability to have compose file generate `-dev` appendix for the local development version when `make gen app-dev [asc-xxxxxx]`  type of commands is used.
Closes: #380
- [x ] Docs have been added / updated (for bug fixes / features)
Currently `make gen dev` doesn't generate the image name appended with `-dev` version for `app-service-configurable` type of docker services.
This PR will have `make gen app-dev` generate the image name appended with `-dev` version for …
> feat(build): Add -dev appendix to app-service-configurable based service image names for make gen app-dev [asc-xxxx]

- compose-builder/add-taf-app-services.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-no-secty-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-no-secty.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus.yml
TAF App Service tests use `blackbox-tests` profile which has been renamed to `functional-tests`
TAF App Service for function tests has been renamed to `app-service-functional-tests` and the profile changed to use `functional-tests` 
> refactor: Rename TAF App Service blockbox-tests to functional-tests

- compose-builder/add-device-camera.yml
`add-device-camera.yml` service name and port conflict with `add-device-rest.yml`
service name and port are set appropriately for device-camera
> fix: Hanoi - Correct service name and port for device camera

- compose-builder/common-sec-stage-gate.env
- releases/nightly-build/compose-files/docker-compose-nexus-arm64.yml
- releases/nightly-build/compose-files/docker-compose-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-nexus.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus-arm64.yml
- releases/nightly-build/compose-files/taf/docker-compose-taf-perf-nexus.yml
Timeout env for waitFor is added for various services
Closes: #398
New env var `StageGate.WaitFor.Timeout` is added
- [x ] No
> feat(security): Update the sec-bootstrapper env

- compose-builder/Makefile
- compose-builder/README.md
No option to simply add a MQTT Broker. The current `mqtt` option adds a broker but also reconfigures the message bus,
New `mqtt-broker option simply adds the additional MQTT Broker service
Previous `mqtt` option renamed `mqtt-bus` to be more explicit.
> feat: Add mqtt-broker option to generate compose

- compose-builder/Makefile
- compose-builder/README.md
- compose-builder/add-asc-http-export.yml
- compose-builder/add-asc-mqtt-export.yml
- compose-builder/add-device-grove.yml
- compose-builder/add-modbus-simulator.yml
- compose-builder/add-mqtt-broker.yml
- compose-builder/add-mqtt-messagebus.yml
Hanoi Compose Builder doesn't have some new options that users requesting
device-grove YML missing `devices` section
Added these options:
- mqtt-bus (renamed from mqtt to be more explicit)
- mqtt-broker (new)
- asc-http (new)
- asc-mqtt (new)
- modbus-sim (new)
Aslo added this to device-grove yaml
```
devices:
- /dev/i2c-1
```
> feat: Hanoi - Add new compose builder options for 1.3.1

- README.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
- [x ] No
> docs: updated readme to indicate archive status
